(deftheme derekbixler
  "Created 2014-06-03.")

(custom-theme-set-faces
 'derekbixler
 '(default ((t (:family "default" :foundry "default" :width normal :height 1 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#000000" :background "#ffffff" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#656565"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#ddaa6f"))))
 '(minibuffer-prompt ((t (:foreground "#e5786d"))))
 '(highlight ((t (:underline (:color foreground-color :style line) :foreground "#ffffff" :background "#454545"))))
 '(region ((t (:foreground "#f6f3e8" :background "#444444"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:foreground "#f6f3e8" :background "#333366"))))
 '(trailing-whitespace ((t (:background "color-254"))))
 '(font-lock-builtin-face ((t (:foreground "#b81426"))))
 '(font-lock-comment-delimiter-face ((t (:inherit default))))
 '(font-lock-comment-face ((t (:foreground "#745e5e"))))
 '(font-lock-constant-face ((t (:foreground "#b81426"))))
 '(font-lock-doc-face ((t (:background "#f2f2f2" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#000000"))))
 '(font-lock-keyword-face ((t (:foreground "#b81426"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t nil)))
 '(font-lock-regexp-grouping-construct ((t nil)))
 '(font-lock-string-face ((t (:foreground "#ae8a32"))))
 '(font-lock-type-face ((t (:foreground "#b81426"))))
 '(font-lock-variable-name-face ((t (:foreground "#000000"))))
 '(font-lock-warning-face ((t (:foreground "#ccaa8f" :inherit (error)))))
 '(button ((t (:foreground "#f6f3e8" :background "#333333" :inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#8ac6f2"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#e5786d" :inherit (link)))))
 '(fringe ((t (:background "#303030"))))
 '(header-line ((t (:underline (:color foreground-color :style line) :inverse-video nil :foreground "#e7f6da" :background "#303030" :inherit (mode-line)))))
