;; Red: #B81426
;; Gold: #AE8A3E
;; Pale: #745E5E

(eval-when-compile
  (require 'color-theme))

(defun color-theme-marlboro ()
  "Color theme by Michael Soulier, created 2003-03-26."
  (interactive)
  (color-theme-install
   '(color-theme-marlboro
     ((background-color . "#ffffff")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "#000000")
      (foreground-color . "#000000")
      (mouse-color . "#000000"))
     (default ((t (:background "#ffffff" :foreground "#000000"))))
     (Info-title-1-face ((t (nil))))
     (Info-title-2-face ((t (nil))))
     (Info-title-3-face ((t (nil))))
     (Info-title-4-face ((t (nil))))
     (bold ((t (nil))))
     (border ((t (:background "black"))))
     (comint-highlight-input ((t ((nil)))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (cperl-array-face ((t (:foreground "brown"))))
     (cperl-hash-face ((t (:foreground "red"))))
     (cperl-nonoverridable-face ((t (:foreground "#008b8b"))))
     (cursor ((t (:background "#000000"))))
     (fixed-pitch ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "#b81426"))))
     (font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
     (font-lock-comment-face ((t (:foreground "#745e5e"))))
     (font-lock-constant-face ((t (:foreground "#b81426"))))
     (font-lock-doc-face ((t (:inherit font-lock-string-face :background "#f2f2f2"))))
     (font-lock-function-name-face ((t (:foreground "#000000"))))
     (font-lock-keyword-face ((t (:foreground "#b81426"))))
     (font-lock-negation-char-face ((t nil)))
     (font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
     (font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
     (font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
     (font-lock-string-face ((t (:foreground "#ae8a32"))))
     (font-lock-type-face ((t (:foreground "#b81426"))))
 	 (font-lock-variable-name-face ((t (:foreground "#000000"))))
     (fringe ((t (:background "#e5e5e5"))))
     (header-line ((t (:background "grey90" :foreground "grey20"))))
     (highlight ((t (:background "darkseagreen2"))))
     (info-header-node ((t (nil))))
     (info-header-xref ((t (nil))))
     (info-menu-5 ((t (:foreground "red1"))))
     (info-menu-header ((t ((nil)))))
     (info-node ((t (:italic (italic oblique) (nil) :foreground "brown"))))
     (info-xref ((t ((nil) :foreground "magenta4"))))
     (isearch ((t (:background "magenta4" :foreground "lightskyblue1"))))
     (isearch-lazy-highlight-face ((t (:background "paleturquoise"))))
     (italic ((t (:italic (italic oblique)))))
     (menu ((t (nil))))
     (mode-line ((t (:background "grey75" :foreground "black"))))
     (mouse ((t (:background "#000000"))))
     (region ((t (:background "lightgoldenrod2"))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (scroll-bar ((t (:background "grey75" :foreground "#000000"))))
     (secondary-selection ((t (:background "yellow"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (show-paren-match-face ((t (:background "turquoise"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (tool-bar ((t (:background "grey75" :foreground "black"))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (nil))))
     (widget-button-face ((t ((nil)))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "dark green"))))
     (widget-field-face ((t (:background "gray85"))))
     (widget-inactive-face ((t (:foreground "dim gray"))))
     (widget-single-line-field-face ((t (:background "gray85")))))))
